version: "2"
services:
  postgres:
    image: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    container_name: 'binanceplus-db'
    restart: 'always'
    env_file:
      - _database.env
    ports:
      - '5432:5432'
    networks:
      - binance_plus

  binance_plus-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: binance_plus-backend:latest
    container_name: binance_plus-backend
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - '3836:3836'
      - '3834:3834'
    networks:
      - binance_plus
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - binance_plus    
      
networks:
  binance_plus:             
volumes:
  postgres-data:
  cache:
