version: "2"
services:
  postgres:
    image: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    container_name: 'binanceplus-db'
    restart: 'always'
    env_file:
      - _database.env
    ports:
      - '5432:5432'
    networks:
      - binance_plus

  binance_plus-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: binance_plus-backend:latest
    container_name: binance_plus-backend
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - '3836:3836'
    networks:
      - binance_plus
      
networks:
  binance_plus:             
volumes:
  postgres-data:
