version: "2"
services:
  binance_plus-backend:
    build: .
    image: binance_plus-backend:latest
    container_name: binance_plus-backend
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
      - .env:/app/.env

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rnssolution@1234
      - MYSQL_PASSWORD=rnssolution@1234
      - MYSQL_USER=Binance+
      - MYSQL_DATABASE=Binance+
    volumes:
      - mysql-data:/var/lib/mysql 
             
volumes:
  mysql-data:
